# this is a conda environment for my general-use shell tools
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - socat # for proxies
  - python=3.11 # pin to speed up solve time

  # git/github
  - git>=2.3
  - git-lfs
  - git-filter-repo
  - gh # github cli
  - pre-commit

  # file transfer
  - wget
  - rclone # cloud storage access

  # searching
  - fzf # awesome file finder
  - the_silver_searcher # better grep (shortcut = ag)
  - ripgrep # fastest grep (shortcut = rg)
  - tree

  # file processing
  - csvkit # csv manipulation
  - datamash # bash table operations
  - pandoc # doc conversion
  - parallel # GNU parallel
  - tar
  - pigz # parallel gzip
  - ncdu # disk usage
  - jq # JSON processing
  - rename # batch renaming

  # bioinformatics
  - seqkit # fastq/a operations
  - htslib>=1.15
  - samtools>=1.15
  - bcftools>=1.15
  - bedtools>=2.30.0
  - plink2
  - plink
  - gffutils
  - gffread
  - biopython
  - gtfparse

  # data science
  - numpy
  - pandas
  - seaborn
  - black
  - joblib
  - tqdm

  # jupyter
  - jupyterlab
  - black-jupyter
  - nb_conda_kernels
  - nbdime
  - nbconvert
